### ISSUE TITLE
360 rotation tween functions don't work.

### ISSUE THREAD

**Issue by FullStackForger** [jeffreylanters/unity-tweens#32]
**Describe the bug**
360 rotation tweens doesn't seem to be working.

**To Reproduce**
1. Create an object in the scene.
2. run `TweenLocalRotationX` function on it, eg: 
```
gameObject.TweenLocalRotationX(360f, 1f).SetEaseBackIn()
```

**Expected behavior**
 Object should rotate 360 degrees around x Axis over 1000ms. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: windows
 - Version: [Latest](https://github.com/jeffreylanters/unity-tweens/commit/976a038bbb3923eb39986cc4b5af98f363795f23)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by RyanJVR** [comment]
Yes I've just come across this as well. Can't rotate past 180 or -180 when using TweenLocalRotationZ on a RecTransform
OS: windows
Version: [Latest](https://github.com/jeffreylanters/unity-tweens/commit/976a038bbb3923eb39986cc4b5af98f363795f23)

**Comment by FullStackForger** [comment]
small bump to reopen it perhaps?

**Comment by derek-vellocet** [comment]
@jeffreylanters I'm seeing this issue as well, I believe it's related to the use of Quaternion.Euler with values greater than 180.

**Comment by derek-vellocet** [comment]
For anyone with this issue, as a workaround you can just tween a float value and manually assign the rotation.

```
this.TweenValueFloat(360.0f, 1.0f, value =>
{
    this.transform.localRotation = Quaternion.Euler(Vector3.one * value);
});
```

**Comment by jeffreylanters** [comment]
This is intended behavior, since when an object is rotated to for example to 355, and you want it to go back to 0, you most likely don't want it to rotate back a full circle, but rather just the 5 degrees. Otherwise you'd had to keep track of its rotation all the time in order to prevent this from happening.

Derek's solution is the way to work around this. But I will look into an option to disable this behavior in the near future.
