### ISSUE TITLE
Awaitable tweens

### ISSUE THREAD

**Issue by f1yingbanana** [jeffreylanters/unity-tweens#45]
Tweens 3.0 looks shiny! It'd be nice if it still supports Tasks like it did in 2.0 though. Completion handlers are okay but they break the logic flow a bit 🌵

**Comment by jeffreylanters** [comment]
Hi! Thank you for your suggestion, I've added it to the development list and will pick it up soon! 🙌🏼

**Comment by hsandt** [comment]
That's great, but note that Task utilities like `WhenAll` won't be available.

The issue is closed, but I'll leave a link to this thread for users looking for help:
https://discussions.unity.com/t/awaitables-whenall/1551331

The proposed solutions are:
- use [UniTask](https://github.com/Cysharp/UniTask?tab=readme-ov-file#vs-awaitable) `WhenAll` or `AsUniTask`
- `foreach` awaitable, `await` it
- same but also catching exceptions if that matters and performance is less critical (sisus_co's custom [AwaitableUtility](https://github.com/timo-sisus/awaitable-utility/edit/main/AwaitableUtility))
